=== xxxandriyxxx/task15_json/src/main/resources/json/tariffsSchema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "tariffNo",
      "name",
      "operatorName",
      "payroll",
      "callPrices",
      "smsPrice",
      "parameters"
    ],
    "properties": {
      "tariffNo": {
        "$id": "#/items/properties/tariffNo",
        "type": "integer",
        "title": "The TariffNo Schema"
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema"
      },
      "operatorName": {
        "$id": "#/items/properties/operatorName",
        "type": "string",
        "title": "The Operatorname Schema"
      },
      "payroll": {
        "$id": "#/items/properties/payroll",
        "type": "number",
        "title": "The Payroll Schema",
        "default": 0.0,
        "minimum": 0.0
      },
      "callPrices": {
        "$id": "#/items/properties/callPrices",
        "type": "object",
        "title": "The Callprices Schema",
        "required": [
          "inside",
          "outside",
          "landlinePhone"
        ],
        "properties": {
          "inside": {
            "$id": "#/items/properties/callPrices/properties/inside",
            "type": "integer",
            "title": "The Inside Schema",
            "default": 0,
            "minimum": 0.0,
            "maximum": 100.0
          },
          "outside": {
            "$id": "#/items/properties/callPrices/properties/outside",
            "type": "integer",
            "title": "The Outside Schema",
            "default": 0,
            "minimum": 0.0,
            "maximum": 100.0
          },
          "landlinePhone": {
            "$id": "#/items/properties/callPrices/properties/landlinePhone",
            "type": "integer",
            "title": "The Landlinephone Schema",
            "default": 0,
            "minimum": 0.0,
            "maximum": 100.0
          }
        }
      },
      "smsPrice": {
        "$id": "#/items/properties/smsPrice",
        "type": "integer",
        "title": "The Smsprice Schema",
        "default": 0,
        "minimum": 0.0,
        "maximum": 100.0
      },
      "parameters": {
        "$id": "#/items/properties/parameters",
        "type": "object",
        "title": "The Parameters Schema",
        "required": [
          "favoriteNumbers",
          "tariffing",
          "connectionPayment"
        ],
        "properties": {
          "favoriteNumbers": {
            "$id": "#/items/properties/parameters/properties/favoriteNumbers",
            "type": "integer",
            "title": "The Favoritenumbers Schema",
            "default": 0,
            "minimum": 0.0
          },
          "tariffing": {
            "$id": "#/items/properties/parameters/properties/tariffing",
            "type": "string",
            "enum": [
              "PER_1_MINUTE",
              "PER_15_SECONDS"
            ],
            "title": "The Tariffing Schema",
            "examples": [
              "PER_1_MINUTE",
              "PER_15_SECONDS"
            ]
          },
          "connectionPayment": {
            "$id": "#/items/properties/parameters/properties/connectionPayment",
            "type": "number",
            "title": "The Connectionpayment Schema",
            "default": 0.0,
            "minimum": 0.0
          }
        }
      }
    }
  }
}

=== xxxandriyxxx/task15_json/src/main/resources/tariffsSortPayroll.json
[
  {
    "tariffNo": 3,
    "name": "Bomba",
    "operatorName": "Lifecell",
    "payroll": 100.0,
    "callPrices": {
      "inside": 0,
      "outside": 50,
      "landlinePhone": 50
    },
    "smsPrice": 49,
    "parameters": {
      "favoriteNumbers": 4,
      "tariffing": "PER_15_SECONDS",
      "connectionPayment": 0.0
    }
  },
  {
    "tariffNo": 2,
    "name": "4G Smart",
    "operatorName": "Vodafone",
    "payroll": 150.0,
    "callPrices": {
      "inside": 10,
      "outside": 80,
      "landlinePhone": 99
    },
    "smsPrice": 50,
    "parameters": {
      "favoriteNumbers": 1,
      "tariffing": "PER_1_MINUTE",
      "connectionPayment": 5.5
    }
  },
  {
    "tariffNo": 0,
    "name": "Super Unlim",
    "operatorName": "Kyivstar",
    "payroll": 250.0,
    "callPrices": {
      "inside": 0,
      "outside": 10,
      "landlinePhone": 20
    },
    "smsPrice": 15,
    "parameters": {
      "favoriteNumbers": 5,
      "tariffing": "PER_1_MINUTE",
      "connectionPayment": 25.5
    }
  },
  {
    "tariffNo": 1,
    "name": "Super Net",
    "operatorName": "Kyivstar",
    "payroll": 300.0,
    "callPrices": {
      "inside": 0,
      "outside": 35,
      "landlinePhone": 45
    },
    "smsPrice": 20,
    "parameters": {
      "favoriteNumbers": 2,
      "tariffing": "PER_15_SECONDS",
      "connectionPayment": 14.99
    }
  },
  {
    "tariffNo": 4,
    "name": "Business",
    "operatorName": "Lifecell",
    "payroll": 350.0,
    "callPrices": {
      "inside": 0,
      "outside": 10,
      "landlinePhone": 10
    },
    "smsPrice": 25,
    "parameters": {
      "favoriteNumbers": 10,
      "tariffing": "PER_1_MINUTE",
      "connectionPayment": 10.0
    }
  }
]
